# Generated by Django 5.1.4 on 2025-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_projetc', '0002_remove_link_series_link_ep1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_series',
            name='ep_name',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
