# Generated by Django 5.1.4 on 2025-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_projetc', '0003_alter_link_series_ep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_series',
            name='ep_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
