# Generated by Django 5.1.4 on 2025-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_projetc', '0004_alter_link_series_ep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_series',
            name='id_vinculado',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
