# Generated by Django 5.1.4 on 2025-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_projetc', '0005_link_series_id_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_series',
            name='ep_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
